"""Orchestrate an end-to-end dependency update.

Clones a repo, reuses the existing scan/check/bump pipeline to find outdated
dependencies, rewrites declared manifests, then pushes branch(es) and opens
PR/MR(s) against the default branch. Network/forge access is injectable so the
whole flow is testable offline.
"""

from __future__ import annotations

import re
import shutil
import tempfile
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

from depfresh_pro import vcs
from depfresh.bump import BumpItem, BumpPlan, build_bump_plan
from depfresh.config import DepfreshConfig, ForgeConfig
from depfresh_pro.editors.registry import find_editor
from depfresh_pro.forge import Forge, detect_forge, make_request
from depfresh_pro.forge.detect import parse_repo_url
from depfresh.resolver import check_updates
from depfresh.scanner import scan

GROUPINGS = ("all", "ecosystem", "dependency")
_CLONE_USER = {"github": "x-access-token", "gitlab": "oauth2"}


class UpdateError(RuntimeError):
    """The update could not be completed."""


@dataclass
class UpdateGroup:
    key: str  # "all" | ecosystem | package name
    branch: str
    title: str
    items: list[BumpItem]
    files_changed: list[str] = field(default_factory=list)
    applied_items: list[BumpItem] = field(default_factory=list)
    request_url: str | None = None
    pushed: bool = False
    diff: str = ""
    skipped_reason: str | None = None


@dataclass
class UpdateRun:
    repo: str
    base_branch: str
    dry_run: bool
    groups: list[UpdateGroup] = field(default_factory=list)

    @property
    def opened(self) -> list[UpdateGroup]:
        return [g for g in self.groups if g.request_url]


def _normalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _slug(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "-", name).strip("-").lower() or "dep"


def _guess_kind(host: str) -> str | None:
    h = host.lower()
    if "github" in h:
        return "github"
    if "gitlab" in h:
        return "gitlab"
    return None


def _count_phrase(n: int) -> str:
    return f"{n} dependency" if n == 1 else f"{n} dependencies"


def _title(grouping: str, key: str, items: Sequence[BumpItem]) -> str:
    """Human title for a group of ``items`` under ``grouping`` (``key`` is the
    ecosystem for ecosystem grouping). Computed from the items it is given, so
    re-titling from the *applied* items keeps the title honest when some planned
    bumps are skipped."""
    if grouping == "dependency":
        item = items[0]
        return f"Update {item.name} to {item.latest}"
    if grouping == "ecosystem":
        return f"Update {_count_phrase(len(items))} ({key})"
    return f"Update {_count_phrase(len(items))}"


def _body(items: Sequence[BumpItem]) -> str:
    lines = ["Automated dependency update generated by depfresh.", ""]
    lines += [f"- **{it.name}** ({it.ecosystem}) → {it.latest}" for it in items]
    return "\n".join(lines)


def _plan_groups(plan: BumpPlan, grouping: str, prefix: str) -> list[UpdateGroup]:
    if grouping == "dependency":
        # Branch name is fixed per package (no version) so re-runs reuse the same
        # branch/MR as new releases land; the version only appears in the title.
        return [
            UpdateGroup(
                key=item.name,
                branch=f"{prefix}{_slug(item.name)}",
                title=_title(grouping, item.name, [item]),
                items=[item],
            )
            for item in plan.items
        ]
    if grouping == "ecosystem":
        by_eco: dict[str, list[BumpItem]] = {}
        for item in plan.items:
            by_eco.setdefault(item.ecosystem, []).append(item)
        return [
            UpdateGroup(
                key=eco,
                branch=f"{prefix}{eco}-updates",
                title=_title(grouping, eco, items),
                items=items,
            )
            for eco, items in sorted(by_eco.items())
        ]
    # default: everything in one group
    if not plan.items:
        return []
    return [
        UpdateGroup(
            key="all",
            branch=f"{prefix}updates",
            title=_title(grouping, "all", list(plan.items)),
            items=list(plan.items),
        )
    ]


def _apply_items(root: Path, items: Sequence[BumpItem]) -> tuple[list[str], list[BumpItem]]:
    """Rewrite declared manifests for ``items``.

    Returns ``(changed_files, applied_items)``: the manifest paths actually
    written, and the items that produced at least one real edit. The PR/MR body
    is built from ``applied_items`` so it describes only what changed — not what
    was merely planned (a range bump skipped to keep the constraint satisfiable,
    or a lockfile-only occurrence with no editor).
    """
    # Collect edits per manifest so a file with several bumps is written once.
    edits: dict[str, list[tuple[BumpItem, str | None, str]]] = {}
    for item in items:
        if item.latest is None:
            continue
        for occ in item.occurrences:
            edits.setdefault(occ.manifest, []).append((item, occ.current, item.latest))

    changed: list[str] = []
    applied: set[tuple[str, str]] = set()
    for manifest_path, ops in edits.items():
        editor = find_editor(Path(manifest_path).name)
        if editor is None:  # lockfile or unsupported -> skip
            continue
        file = root / manifest_path
        try:
            text = file.read_text(encoding="utf-8")
        except OSError:
            continue
        new_text = text
        for item, current, latest in ops:
            new_text, did = editor.apply(new_text, item.name, current, latest)
            if did:
                applied.add((item.ecosystem, item.name))
        if new_text != text:
            file.write_text(new_text, encoding="utf-8")
            changed.append(manifest_path)
    applied_items = [it for it in items if (it.ecosystem, it.name) in applied]
    return sorted(changed), applied_items


def _resolve_forge(
    repo_url: str, token: str | None, config: DepfreshConfig, request
) -> tuple[Forge, str | None]:
    ref = parse_repo_url(repo_url)
    guessed = _guess_kind(ref.host)
    fcfg: ForgeConfig = (
        config.for_forge(guessed) if guessed else next(iter(config.forges.values()), ForgeConfig())
    )
    token = token or fcfg.token
    forge = detect_forge(
        repo_url, token or "", request, kind=fcfg.kind or guessed, api_base=fcfg.base_url
    )
    return forge, token


def run_update(
    repo_url: str,
    token: str | None = None,
    *,
    config: DepfreshConfig | None = None,
    grouping: str = "all",
    branch_prefix: str = "depfresh/",
    base: str | None = None,
    exclude: Sequence[str] = (),
    ecosystems: Sequence[str] | None = None,
    dry_run: bool = False,
    delete_branch: bool = True,
    timeout: float = 10.0,
    max_workers: int = 16,
    fetch=None,
    request=None,
    forge: Forge | None = None,
    clone_url: str | None = None,
) -> UpdateRun:
    """Clone ``repo_url``, bump outdated declared deps, and open PR/MR(s).

    ``forge``/``clone_url``/``fetch``/``request`` are injection points for tests
    (a fake forge, a local bare repo as the remote, canned registry/HTTP).
    """
    if grouping not in GROUPINGS:
        raise UpdateError(f"unknown grouping {grouping!r}; choose from {', '.join(GROUPINGS)}")
    config = config or DepfreshConfig()
    if forge is None:
        forge, token = _resolve_forge(repo_url, token, config, request or make_request())

    # No token is fine for public repos or injected fakes; a private clone/push
    # without one will simply fail loudly.
    auth_cfg = vcs.auth_config(_CLONE_USER.get(forge.name, "oauth2"), token) if token else ()
    eco_filter = {e.lower() for e in ecosystems} if ecosystems else None
    exclude_set = {_normalize(e) for e in exclude}

    workdir = Path(tempfile.mkdtemp(prefix="depfresh-"))
    clone_dir = workdir / "repo"
    try:
        # --no-single-branch so existing bot branches get a remote-tracking ref
        # (enables force-with-lease and no-op detection on re-runs).
        vcs.clone(clone_url or repo_url, clone_dir, config=auth_cfg, depth=1, single_branch=False)
        default_local = vcs.current_branch(clone_dir)
        base_branch = base or _safe_default_branch(forge) or default_local

        if delete_branch and not dry_run:
            # Best-effort: configure the forge to drop merged branches.
            try:
                forge.ensure_auto_delete_on_merge()
            except Exception:  # noqa: BLE001 - never fail the run over a settings call
                pass

        result = scan(clone_dir)
        updates = check_updates(
            result, config=config, fetch=fetch, max_workers=max_workers, timeout=timeout
        )
        plan = build_bump_plan(result, updates)
        plan = _filter_plan(plan, eco_filter, exclude_set)

        run = UpdateRun(repo=repo_url, base_branch=base_branch, dry_run=dry_run)
        for group in _plan_groups(plan, grouping, branch_prefix):
            _process_group(
                group,
                clone_dir,
                default_local,
                base_branch,
                dry_run,
                auth_cfg,
                forge,
                delete_branch,
                grouping,
            )
            run.groups.append(group)
        return run
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def _safe_default_branch(forge: Forge) -> str | None:
    try:
        return forge.default_branch() or None
    except Exception:  # noqa: BLE001 - fall back to the cloned HEAD
        return None


def _filter_plan(plan: BumpPlan, eco_filter: set[str] | None, exclude: set[str]) -> BumpPlan:
    items = [
        it
        for it in plan.items
        if _normalize(it.name) not in exclude
        and (eco_filter is None or it.ecosystem.lower() in eco_filter)
    ]
    return BumpPlan(items=items)


def _process_group(
    group: UpdateGroup,
    clone_dir: Path,
    default_local: str,
    base_branch: str,
    dry_run: bool,
    auth_cfg,
    forge: Forge,
    delete_branch: bool,
    grouping: str,
) -> None:
    remote_ref = f"origin/{group.branch}"
    branch_exists = vcs.remote_ref_exists(clone_dir, remote_ref)

    if not dry_run:
        # Always cut from the current default so the branch is "default + bumps".
        vcs.create_branch(clone_dir, group.branch)
    group.files_changed, group.applied_items = _apply_items(clone_dir, group.items)

    if not group.files_changed:
        group.skipped_reason = "no editable manifests changed (e.g. lockfile-only)"
        if not dry_run:
            vcs.checkout(clone_dir, default_local)
        return

    # Re-title from what actually changed: a planned bump may have been skipped
    # (e.g. a range bump that would breach its upper bound), so the count/version
    # in the title must reflect the applied items, not the planned ones.
    group.title = _title(grouping, group.key, group.applied_items)

    if dry_run:
        group.diff = vcs.diff(clone_dir)
        vcs.discard_changes(clone_dir)
        return

    vcs.stage(clone_dir, group.files_changed)
    vcs.commit(clone_dir, group.title)

    # Idempotent re-run: if the bumped tree already matches what's on the remote
    # branch, don't churn — keep the branch and reuse the open request's link.
    if branch_exists and vcs.tree_hash(clone_dir, "HEAD") == vcs.tree_hash(clone_dir, remote_ref):
        group.skipped_reason = "branch already up to date"
        group.request_url = forge.existing_request(group.branch)
        vcs.checkout(clone_dir, default_local)
        return

    vcs.push(clone_dir, group.branch, config=auth_cfg, force=branch_exists)
    group.pushed = True
    group.request_url = forge.open_request(
        base=base_branch,
        head=group.branch,
        title=group.title,
        body=_body(group.applied_items),
        delete_source_branch=delete_branch,
    )
    vcs.checkout(clone_dir, default_local)
