"""Orchestrate an end-to-end dependency update.

Clones a repo, reuses the existing scan/check/bump pipeline to find outdated
dependencies, rewrites declared manifests, then pushes branch(es) and opens
PR/MR(s) against the default branch. Network/forge access is injectable so the
whole flow is testable offline.
"""

from __future__ import annotations

import re
import shutil
import tempfile
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

from depfresh import vcs
from depfresh.bump import BumpItem, BumpPlan, build_bump_plan
from depfresh.config import DepfreshConfig, ForgeConfig
from depfresh.editors.registry import find_editor
from depfresh.forge import Forge, detect_forge, make_request
from depfresh.forge.detect import parse_repo_url
from depfresh.resolver import check_updates
from depfresh.scanner import scan

GROUPINGS = ("all", "ecosystem", "dependency")
_CLONE_USER = {"github": "x-access-token", "gitlab": "oauth2"}


class UpdateError(RuntimeError):
    """The update could not be completed."""


@dataclass
class UpdateGroup:
    key: str  # "all" | ecosystem | package name
    branch: str
    title: str
    items: list[BumpItem]
    files_changed: list[str] = field(default_factory=list)
    request_url: str | None = None
    pushed: bool = False
    diff: str = ""
    skipped_reason: str | None = None


@dataclass
class UpdateRun:
    repo: str
    base_branch: str
    dry_run: bool
    groups: list[UpdateGroup] = field(default_factory=list)

    @property
    def opened(self) -> list[UpdateGroup]:
        return [g for g in self.groups if g.request_url]


def _normalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _slug(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "-", name).strip("-").lower() or "dep"


def _guess_kind(host: str) -> str | None:
    h = host.lower()
    if "github" in h:
        return "github"
    if "gitlab" in h:
        return "gitlab"
    return None


def _count_phrase(n: int) -> str:
    return f"{n} dependency" if n == 1 else f"{n} dependencies"


def _body(items: Sequence[BumpItem]) -> str:
    lines = ["Automated dependency update generated by depfresh.", ""]
    lines += [f"- **{it.name}** ({it.ecosystem}) → {it.latest}" for it in items]
    return "\n".join(lines)


def _plan_groups(plan: BumpPlan, grouping: str, prefix: str) -> list[UpdateGroup]:
    if grouping == "dependency":
        return [
            UpdateGroup(
                key=item.name,
                branch=f"{prefix}{_slug(item.name)}-{item.latest}",
                title=f"Update {item.name} to {item.latest}",
                items=[item],
            )
            for item in plan.items
        ]
    if grouping == "ecosystem":
        by_eco: dict[str, list[BumpItem]] = {}
        for item in plan.items:
            by_eco.setdefault(item.ecosystem, []).append(item)
        return [
            UpdateGroup(
                key=eco,
                branch=f"{prefix}{eco}-updates",
                title=f"Update {_count_phrase(len(items))} ({eco})",
                items=items,
            )
            for eco, items in sorted(by_eco.items())
        ]
    # default: everything in one group
    if not plan.items:
        return []
    return [
        UpdateGroup(
            key="all",
            branch=f"{prefix}updates",
            title=f"Update {_count_phrase(len(plan.items))}",
            items=list(plan.items),
        )
    ]


def _apply_items(root: Path, items: Sequence[BumpItem]) -> list[str]:
    """Rewrite declared manifests for ``items``; return changed file paths."""
    # Collect edits per manifest so a file with several bumps is written once.
    edits: dict[str, list[tuple[str, str | None, str]]] = {}
    for item in items:
        if item.latest is None:
            continue
        for occ in item.occurrences:
            edits.setdefault(occ.manifest, []).append((item.name, occ.current, item.latest))

    changed: list[str] = []
    for manifest_path, ops in edits.items():
        editor = find_editor(Path(manifest_path).name)
        if editor is None:  # lockfile or unsupported -> skip
            continue
        file = root / manifest_path
        try:
            text = file.read_text(encoding="utf-8")
        except OSError:
            continue
        new_text = text
        touched = False
        for name, current, latest in ops:
            new_text, did = editor.apply(new_text, name, current, latest)
            touched = touched or did
        if touched and new_text != text:
            file.write_text(new_text, encoding="utf-8")
            changed.append(manifest_path)
    return sorted(changed)


def _resolve_forge(
    repo_url: str, token: str | None, config: DepfreshConfig, request
) -> tuple[Forge, str | None]:
    ref = parse_repo_url(repo_url)
    guessed = _guess_kind(ref.host)
    fcfg: ForgeConfig = (
        config.for_forge(guessed) if guessed else next(iter(config.forges.values()), ForgeConfig())
    )
    token = token or fcfg.token
    forge = detect_forge(
        repo_url, token or "", request, kind=fcfg.kind or guessed, api_base=fcfg.base_url
    )
    return forge, token


def run_update(
    repo_url: str,
    token: str | None = None,
    *,
    config: DepfreshConfig | None = None,
    grouping: str = "all",
    branch_prefix: str = "depfresh/",
    base: str | None = None,
    exclude: Sequence[str] = (),
    ecosystems: Sequence[str] | None = None,
    dry_run: bool = False,
    timeout: float = 10.0,
    max_workers: int = 16,
    fetch=None,
    request=None,
    forge: Forge | None = None,
    clone_url: str | None = None,
) -> UpdateRun:
    """Clone ``repo_url``, bump outdated declared deps, and open PR/MR(s).

    ``forge``/``clone_url``/``fetch``/``request`` are injection points for tests
    (a fake forge, a local bare repo as the remote, canned registry/HTTP).
    """
    if grouping not in GROUPINGS:
        raise UpdateError(f"unknown grouping {grouping!r}; choose from {', '.join(GROUPINGS)}")
    config = config or DepfreshConfig()
    if forge is None:
        forge, token = _resolve_forge(repo_url, token, config, request or make_request())

    # No token is fine for public repos or injected fakes; a private clone/push
    # without one will simply fail loudly.
    auth_cfg = vcs.auth_config(_CLONE_USER.get(forge.name, "oauth2"), token) if token else ()
    eco_filter = {e.lower() for e in ecosystems} if ecosystems else None
    exclude_set = {_normalize(e) for e in exclude}

    workdir = Path(tempfile.mkdtemp(prefix="depfresh-"))
    clone_dir = workdir / "repo"
    try:
        vcs.clone(clone_url or repo_url, clone_dir, config=auth_cfg, depth=1)
        default_local = vcs.current_branch(clone_dir)
        base_branch = base or _safe_default_branch(forge) or default_local

        result = scan(clone_dir)
        updates = check_updates(
            result, config=config, fetch=fetch, max_workers=max_workers, timeout=timeout
        )
        plan = build_bump_plan(result, updates)
        plan = _filter_plan(plan, eco_filter, exclude_set)

        run = UpdateRun(repo=repo_url, base_branch=base_branch, dry_run=dry_run)
        for group in _plan_groups(plan, grouping, branch_prefix):
            _process_group(group, clone_dir, default_local, base_branch, dry_run, auth_cfg, forge)
            run.groups.append(group)
        return run
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def _safe_default_branch(forge: Forge) -> str | None:
    try:
        return forge.default_branch() or None
    except Exception:  # noqa: BLE001 - fall back to the cloned HEAD
        return None


def _filter_plan(plan: BumpPlan, eco_filter: set[str] | None, exclude: set[str]) -> BumpPlan:
    items = [
        it
        for it in plan.items
        if _normalize(it.name) not in exclude
        and (eco_filter is None or it.ecosystem.lower() in eco_filter)
    ]
    return BumpPlan(items=items)


def _process_group(
    group: UpdateGroup,
    clone_dir: Path,
    default_local: str,
    base_branch: str,
    dry_run: bool,
    auth_cfg,
    forge: Forge,
) -> None:
    if not dry_run:
        vcs.create_branch(clone_dir, group.branch)
    group.files_changed = _apply_items(clone_dir, group.items)

    if not group.files_changed:
        group.skipped_reason = "no editable manifests changed (e.g. lockfile-only)"
        if not dry_run:
            vcs.checkout(clone_dir, default_local)
        return

    if dry_run:
        group.diff = vcs.diff(clone_dir)
        vcs.discard_changes(clone_dir)
        return

    vcs.stage(clone_dir, group.files_changed)
    vcs.commit(clone_dir, group.title)
    vcs.push(clone_dir, group.branch, config=auth_cfg)
    group.pushed = True
    group.request_url = forge.open_request(
        base=base_branch, head=group.branch, title=group.title, body=_body(group.items)
    )
    vcs.checkout(clone_dir, default_local)
